project:
  type: website
  output-dir: _site
  resources:
    - CNAME

website:
  title: "Flaky"
  site-url: "https://www.flakypieshop.com"
  search: false
  navbar:
    left:
      - href: de/index.qmd#home
        text: Startseite
      - href: de/index.qmd#about
        text: Über mich
      - href: de/index.qmd#products
        text: Produkte
      - href: de/contact.qmd
        text: Bestellung

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header: head.html

editor: visual
