project:
  type: website
  output-dir: _site
  resources:
    - CNAME

website:
  title: "Flaky"
  site-url: "https://www.flakypieshop.com"
  search: false
  navbar:
    left:
      - text: Startseite
        href: ./index.html#home
      - text: Über mich
        href: ./index.html#about
      - text: Produkte
        href: ./index.html#products
      - text: Bestellung
        href: ./contact.html

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header: head.html

editor: visual
